/// Demo data adapter — converts the existing `mock_data.dart` into real
/// model objects flagged with `isDemo: true`.
///
/// Strategy:
///   - When the user is not signed in, providers show demo rows so the app
///     never feels empty during design review.
///   - When the user IS signed in but Supabase returns zero rows yet
///     (e.g. a new investor whose Zoho records haven't synced), demo rows
///     are still shown so the UI has substance — they're tagged isDemo.
///   - The moment a real row arrives, demo rows are filtered out by ID
///     prefix (`demo:` is reserved for them).
///
/// All demo IDs are prefixed `demo:` so they can never collide with real
/// UUIDs from Supabase.
library;

import 'package:flutter/material.dart';
import 'package:arl_app/core/mock/mock_data.dart';
import 'package:arl_app/features/activity/models/notification.dart';
import 'package:arl_app/features/documents/models/document.dart';
import 'package:arl_app/features/financials/models/payout.dart';
import 'package:arl_app/features/gallery/models/gallery_photo.dart';
import 'package:arl_app/features/home/models/portfolio_summary.dart';
import 'package:arl_app/features/projects/models/project.dart';
import 'package:arl_app/features/projects/models/project_phase.dart';

const String demoIdPrefix = 'demo:';

/// True if [id] was generated by [demoData] (prefixed with [demoIdPrefix]).
/// Useful when the UI needs to special-case demo rows.
bool isDemoId(String id) => id.startsWith(demoIdPrefix);

PortfolioSummary demoPortfolioSummary() => PortfolioSummary(
      investorName: mockPortfolioSummary.investorName,
      totalInvested: mockPortfolioSummary.totalInvested,
      totalReceived: mockPortfolioSummary.totalReceived,
      pendingAmount: mockPortfolioSummary.pendingAmount,
      activeUnits: mockPortfolioSummary.activeUnits,
      nextPayoutAmount: mockPortfolioSummary.nextPayoutAmount,
      nextPayoutDate: mockPortfolioSummary.nextPayoutDate,
      roiPercent: mockPortfolioSummary.roiPercent,
      annualReturns: mockPortfolioSummary.annualReturns,
      isDemo: true,
    );

List<Project> demoProjects() => mockProjects
    .map((m) => Project(
          id: '$demoIdPrefix${m.id}',
          name: m.name,
          cropType: m.cropType,
          location: m.location,
          status: m.status,
          startDate: m.startDate,
          endDate: m.endDate,
          totalUnits: m.totalUnits,
          investedAmount: m.investedAmount,
          progressPercent: m.progressPercent,
          monthOfContract: m.monthOfContract,
          totalMonths: m.totalMonths,
          colorHex: m.colorHex,
          initials: m.initials,
          nextPayoutAmount: m.nextPayoutAmount,
          nextPayoutDate: m.nextPayoutDate,
          cropEmoji: m.cropEmoji,
          isDemo: true,
        ))
    .toList();

List<Payout> demoPayouts({String? projectId}) {
  // Translate mock payouts (string IDs) to demo payouts.
  Iterable<MockPayout> source = mockPayouts;
  if (projectId != null) {
    final stripped = projectId.startsWith(demoIdPrefix)
        ? projectId.substring(demoIdPrefix.length)
        : projectId;
    source = source.where((p) => p.projectId == stripped);
  }
  return source
      .map((m) => Payout(
            id: '$demoIdPrefix${m.id}',
            amount: m.amount,
            projectId: '$demoIdPrefix${m.projectId}',
            projectName: m.projectName,
            status: m.status,
            date: m.date,
            utrRef: m.utrRef,
            isDemo: true,
          ))
      .toList();
}

List<ArlNotification> demoNotifications() => mockNotifications
    .map((m) => ArlNotification(
          id: '$demoIdPrefix${m.id}',
          type: _mapMockNotifTypeToDb(m.type),
          title: m.title,
          body: m.body,
          isRead: m.isRead,
          createdAt: m.timestamp,
          metadata: const {},
          isDemo: true,
        ))
    .toList();

String _mapMockNotifTypeToDb(String mockType) {
  switch (mockType) {
    case 'warning':
      return 'reminder';
    case 'success':
      return 'photo';
    case 'payout':
      return 'payout';
    case 'info':
    default:
      return 'milestone';
  }
}

List<InvestorDocument> demoDocuments() => mockDocuments
    .map((m) => InvestorDocument(
          id: '$demoIdPrefix${m.id}',
          name: m.name,
          category: m.type.toLowerCase().contains('legal')
              ? 'agreement'
              : m.type.toLowerCase().contains('verif')
                  ? 'kyc'
                  : 'other',
          visibility: 'investor',
          signedUrl: '', // demo docs are never opened
          uploadedAt: null,
          isDemo: true,
        ))
    .toList();

List<GalleryPhoto> demoGalleryPhotos({String? projectId}) {
  return mockGalleryPhotos
      .map((m) => GalleryPhoto(
            id: '$demoIdPrefix${m.id}',
            projectId: '$demoIdPrefix${m.projectId}',
            signedUrl: '',
            caption: null,
            takenAt: m.uploadedAt,
            uploadedAt: m.uploadedAt,
            isDemo: true,
          ))
      .toList();
}

/// Demo phases for a given mock project ID (gv|so|va).
/// When the projectId is a real UUID we just return [].
List<ProjectPhase> demoPhases(String projectId) {
  final stripped = projectId.startsWith(demoIdPrefix)
      ? projectId.substring(demoIdPrefix.length)
      : projectId;
  final source = mockPhaseMilestones[stripped] ?? const [];
  var i = 0;
  return source
      .map((m) => ProjectPhase(
            id: '$demoIdPrefix${stripped}_$i',
            projectId: '$demoIdPrefix$stripped',
            name: m.label,
            status: m.isDone ? 'done' : 'pending',
            sortOrder: i++,
            isDemo: true,
          ))
      .toList();
}

/// Strips demo rows from a list whenever any non-demo row is present.
/// Use this to merge real + demo without ever showing both for the same investor.
List<T> mergeWithDemo<T>(
  List<T> real,
  List<T> demo,
  bool Function(T) isDemoOf,
) {
  if (real.isEmpty) return demo;
  // We have real data — drop demo entirely, the user is past the empty state.
  return real.where((r) => !isDemoOf(r)).toList();
}

// ─────────────────────────────────────────────────────────────────────────────
// Curated Demo Persona: Aarav Mehta
// Rich enough to demonstrate all app features for stakeholder demos.
// ─────────────────────────────────────────────────────────────────────────────

/// Demo investor persona: Aarav Mehta, verified KYC, with realistic context.
class DemoInvestor {
  final String id;
  final String name;
  final String email;
  final String? phone;
  final String kycStatus;
  final String bankLastFour;
  final String bankName;
  final DateTime createdAt;

  const DemoInvestor({
    required this.id,
    required this.name,
    required this.email,
    required this.phone,
    required this.kycStatus,
    required this.bankLastFour,
    required this.bankName,
    required this.createdAt,
  });
}

final demoDemoInvestor = DemoInvestor(
  id: '${demoIdPrefix}investor_aarav',
  name: 'Aarav Mehta',
  email: 'aarav@example.com',
  phone: '+91 98765 43210',
  kycStatus: 'verified',
  bankLastFour: '5678',
  bankName: 'HDFC Bank',
  createdAt: DateTime(2025, 6, 15),
);

/// Enhanced projects: Pineapple LLP (active) and Mango LLP (onboarding).
List<Project> demoCuratedProjects() => [
      Project(
        id: '$demoIdPrefix:pineapple_llp',
        name: 'Pineapple LLP',
        cropType: 'Pineapples',
        location: 'Belgaum, Karnataka',
        status: 'operational',
        startDate: DateTime(2024, 6, 1),
        endDate: DateTime(2028, 6, 1),
        totalUnits: 4,
        investedAmount: 12000000.0,
        progressPercent: 58,
        monthOfContract: 20,
        totalMonths: 48,
        colorHex: '#F2DC6B',
        initials: 'PL',
        nextPayoutAmount: 28500.0,
        nextPayoutDate: DateTime(2026, 5, 10),
        cropEmoji: '🍍',
        isDemo: true,
      ),
      Project(
        id: '$demoIdPrefix:mango_llp',
        name: 'Mango LLP',
        cropType: 'Mangoes',
        location: 'Ratnagiri, Maharashtra',
        status: 'pending',
        startDate: DateTime(2026, 5, 1),
        endDate: DateTime(2030, 5, 1),
        totalUnits: 2,
        investedAmount: 6300000.0,
        progressPercent: 0,
        monthOfContract: 0,
        totalMonths: 48,
        colorHex: '#D4AF37',
        initials: 'ML',
        nextPayoutAmount: 0.0,
        nextPayoutDate: null,
        cropEmoji: '🥭',
        isDemo: true,
      ),
    ];

/// 8 payouts: mix of processed and pending, covering last 6 months.
List<Payout> demoCuratedPayouts() => [
      Payout(
        id: '${demoIdPrefix}payout_001',
        amount: 28500.0,
        projectId: '$demoIdPrefix:pineapple_llp',
        projectName: 'Pineapple LLP',
        status: 'processed',
        date: DateTime(2026, 4, 10),
        utrRef: 'HDFC0001234567',
        isDemo: true,
      ),
      Payout(
        id: '${demoIdPrefix}payout_002',
        amount: 26800.0,
        projectId: '$demoIdPrefix:pineapple_llp',
        projectName: 'Pineapple LLP',
        status: 'processed',
        date: DateTime(2026, 3, 10),
        utrRef: 'HDFC0001234568',
        isDemo: true,
      ),
      Payout(
        id: '${demoIdPrefix}payout_003',
        amount: 28500.0,
        projectId: '$demoIdPrefix:pineapple_llp',
        projectName: 'Pineapple LLP',
        status: 'processed',
        date: DateTime(2026, 2, 10),
        utrRef: 'HDFC0001234569',
        isDemo: true,
      ),
      Payout(
        id: '${demoIdPrefix}payout_004',
        amount: 27200.0,
        projectId: '$demoIdPrefix:pineapple_llp',
        projectName: 'Pineapple LLP',
        status: 'processed',
        date: DateTime(2026, 1, 10),
        utrRef: 'HDFC0001234570',
        isDemo: true,
      ),
      Payout(
        id: '${demoIdPrefix}payout_005',
        amount: 28500.0,
        projectId: '$demoIdPrefix:pineapple_llp',
        projectName: 'Pineapple LLP',
        status: 'processed',
        date: DateTime(2025, 12, 10),
        utrRef: 'HDFC0001234571',
        isDemo: true,
      ),
      Payout(
        id: '${demoIdPrefix}payout_006',
        amount: 29200.0,
        projectId: '$demoIdPrefix:pineapple_llp',
        projectName: 'Pineapple LLP',
        status: 'processed',
        date: DateTime(2025, 11, 10),
        utrRef: 'HDFC0001234572',
        isDemo: true,
      ),
      Payout(
        id: '${demoIdPrefix}payout_007',
        amount: 31500.0,
        projectId: '$demoIdPrefix:pineapple_llp',
        projectName: 'Pineapple LLP',
        status: 'pending',
        date: DateTime(2026, 5, 10),
        utrRef: null,
        isDemo: true,
      ),
      Payout(
        id: '${demoIdPrefix}payout_008',
        amount: 0.0,
        projectId: '$demoIdPrefix:mango_llp',
        projectName: 'Mango LLP',
        status: 'pending',
        date: DateTime(2026, 6, 1),
        utrRef: null,
        isDemo: true,
      ),
    ];

/// 12 gallery photos spread across both projects with captions.
/// Placeholder paths: user should drop real images into assets/images/ if desired.
List<GalleryPhoto> demoCuratedGalleryPhotos() => [
      // Pineapple LLP photos (8)
      GalleryPhoto(
        id: '${demoIdPrefix}photo_001',
        projectId: '$demoIdPrefix:pineapple_llp',
        signedUrl: 'assets/images/placeholder_pineapple_1.png',
        caption: 'Pineapple saplings, Week 4 growth stage.',
        takenAt: DateTime(2026, 4, 15),
        uploadedAt: DateTime(2026, 4, 16),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_002',
        projectId: '$demoIdPrefix:pineapple_llp',
        signedUrl: 'assets/images/placeholder_pineapple_2.png',
        caption: 'Canopy spreading nicely across field section B.',
        takenAt: DateTime(2026, 4, 14),
        uploadedAt: DateTime(2026, 4, 15),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_003',
        projectId: '$demoIdPrefix:pineapple_llp',
        signedUrl: 'assets/images/placeholder_pineapple_3.png',
        caption: 'Flowering begins in northern rows.',
        takenAt: DateTime(2026, 4, 10),
        uploadedAt: DateTime(2026, 4, 11),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_004',
        projectId: '$demoIdPrefix:pineapple_llp',
        signedUrl: 'assets/images/placeholder_pineapple_4.png',
        caption: 'Drip irrigation system performing well.',
        takenAt: DateTime(2026, 4, 8),
        uploadedAt: DateTime(2026, 4, 9),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_005',
        projectId: '$demoIdPrefix:pineapple_llp',
        signedUrl: 'assets/images/placeholder_pineapple_5.png',
        caption: 'Soil health check post-monsoon.',
        takenAt: DateTime(2026, 3, 20),
        uploadedAt: DateTime(2026, 3, 21),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_006',
        projectId: '$demoIdPrefix:pineapple_llp',
        signedUrl: 'assets/images/placeholder_pineapple_6.png',
        caption: 'Mulching completed, disease control active.',
        takenAt: DateTime(2026, 3, 15),
        uploadedAt: DateTime(2026, 3, 16),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_007',
        projectId: '$demoIdPrefix:pineapple_llp',
        signedUrl: 'assets/images/placeholder_pineapple_7.png',
        caption: 'Field overview, uniform growth across units.',
        takenAt: DateTime(2026, 3, 10),
        uploadedAt: DateTime(2026, 3, 11),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_008',
        projectId: '$demoIdPrefix:pineapple_llp',
        signedUrl: 'assets/images/placeholder_pineapple_8.png',
        caption: 'Equipment maintenance completed.',
        takenAt: DateTime(2026, 3, 5),
        uploadedAt: DateTime(2026, 3, 6),
        isDemo: true,
      ),
      // Mango LLP photos (4)
      GalleryPhoto(
        id: '${demoIdPrefix}photo_009',
        projectId: '$demoIdPrefix:mango_llp',
        signedUrl: 'assets/images/placeholder_mango_1.png',
        caption: 'Land preparation underway, soil enrichment phase.',
        takenAt: DateTime(2026, 4, 12),
        uploadedAt: DateTime(2026, 4, 13),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_010',
        projectId: '$demoIdPrefix:mango_llp',
        signedUrl: 'assets/images/placeholder_mango_2.png',
        caption: 'Infrastructure setup, fencing installed.',
        takenAt: DateTime(2026, 4, 8),
        uploadedAt: DateTime(2026, 4, 9),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_011',
        projectId: '$demoIdPrefix:mango_llp',
        signedUrl: 'assets/images/placeholder_mango_3.png',
        caption: 'Nursery saplings ready for transplant.',
        takenAt: DateTime(2026, 4, 5),
        uploadedAt: DateTime(2026, 4, 6),
        isDemo: true,
      ),
      GalleryPhoto(
        id: '${demoIdPrefix}photo_012',
        projectId: '$demoIdPrefix:mango_llp',
        signedUrl: 'assets/images/placeholder_mango_4.png',
        caption: 'Project site overview, ready for May kickoff.',
        takenAt: DateTime(2026, 4, 1),
        uploadedAt: DateTime(2026, 4, 2),
        isDemo: true,
      ),
    ];

/// 6 notifications: mix of read/unread, all 5 notification types.
List<ArlNotification> demoCuratedNotifications() => [
      ArlNotification(
        id: '${demoIdPrefix}notif_001',
        type: 'payout',
        title: 'Payout Credited',
        body:
            'INR 28,500 credited for Pineapple LLP Unit 2. UTR: HDFC0001234567',
        isRead: false,
        createdAt: DateTime(2026, 4, 11),
        metadata: {'amount': '28500', 'project': 'Pineapple LLP'},
        isDemo: true,
      ),
      ArlNotification(
        id: '${demoIdPrefix}notif_002',
        type: 'photo',
        title: 'New Photos Available',
        body:
            'Fresh photos from Pineapple LLP showing healthy flowering stage.',
        isRead: false,
        createdAt: DateTime(2026, 4, 16),
        metadata: {'project': 'Pineapple LLP', 'count': '2'},
        isDemo: true,
      ),
      ArlNotification(
        id: '${demoIdPrefix}notif_003',
        type: 'milestone',
        title: 'Project Milestone',
        body:
            'Canopy spreading reached 75% coverage. Excellent growth trajectory.',
        isRead: true,
        createdAt: DateTime(2026, 4, 10),
        metadata: {'project': 'Pineapple LLP', 'milestone': 'canopy'},
        isDemo: true,
      ),
      ArlNotification(
        id: '${demoIdPrefix}notif_004',
        type: 'reminder',
        title: 'Capital Confirmation Pending',
        body:
            'Mango LLP awaits final capital clearance. Expected by May 1, 2026.',
        isRead: false,
        createdAt: DateTime(2026, 4, 9),
        metadata: {'project': 'Mango LLP', 'status': 'pending'},
        isDemo: true,
      ),
      ArlNotification(
        id: '${demoIdPrefix}notif_005',
        type: 'photo',
        title: 'Progress Update',
        body: 'Mango LLP infrastructure setup completed. Ready for transplant.',
        isRead: true,
        createdAt: DateTime(2026, 4, 6),
        metadata: {'project': 'Mango LLP', 'update': 'infrastructure'},
        isDemo: true,
      ),
      ArlNotification(
        id: '${demoIdPrefix}notif_006',
        type: 'milestone',
        title: 'Operational Milestone Achieved',
        body: 'Pineapple LLP soil health assessment passed all parameters.',
        isRead: true,
        createdAt: DateTime(2026, 3, 21),
        metadata: {'project': 'Pineapple LLP', 'milestone': 'soil_health'},
        isDemo: true,
      ),
    ];

/// 4 documents: one per doc_type (agreement, kyc, other, other).
List<InvestorDocument> demoCuratedDocuments() => [
      InvestorDocument(
        id: '${demoIdPrefix}doc_001',
        name: 'Pineapple LLP Investment Agreement',
        category: 'agreement',
        visibility: 'investor',
        signedUrl: '',
        uploadedAt: DateTime(2024, 6, 15),
        isDemo: true,
      ),
      InvestorDocument(
        id: '${demoIdPrefix}doc_002',
        name: 'KYC Verification Certificate',
        category: 'kyc',
        visibility: 'investor',
        signedUrl: '',
        uploadedAt: DateTime(2025, 6, 10),
        isDemo: true,
      ),
      InvestorDocument(
        id: '${demoIdPrefix}doc_003',
        name: 'Payout Statement Q4 FY25',
        category: 'other',
        visibility: 'project',
        signedUrl: '',
        uploadedAt: DateTime(2026, 1, 15),
        isDemo: true,
      ),
      InvestorDocument(
        id: '${demoIdPrefix}doc_004',
        name: 'Mango LLP Pre-Launch Disclosure',
        category: 'other',
        visibility: 'common',
        signedUrl: '',
        uploadedAt: DateTime(2026, 3, 20),
        isDemo: true,
      ),
    ];

/// Helper: Show a SnackBar indicating demo mode changes are not saved.
void demoMutationToast(BuildContext context, String message) {
  ScaffoldMessenger.of(context).showSnackBar(
    SnackBar(
      content: Text(
        'Demo mode — $message not saved.',
        style: const TextStyle(
          fontFamily: 'Inter',
          fontSize: 13,
          color: Color(0xFF3C5152),
        ),
      ),
      duration: const Duration(seconds: 2),
      behavior: SnackBarBehavior.floating,
      backgroundColor: const Color(0xFFF2DC6B),
    ),
  );
}
